apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: go-web-server
          image: ttl.sh/littlejo-webapp:2h
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cluster
