version: 2

project_name: terratest

builds:
  - id: test-binary
    no_main_check: true
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: ""
    flags:
      - -c
      - -o
    command: test
    binary: check-cilium-clustermesh

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
