apiVersion: v1
kind: ConfigMap
metadata:
  name: check-global-services
data:
  check-global-services.sh: |
    svc_name=go-web-server-pod
    clusters=$CLUSTERS_NUMBER

    touch /tmp/clusters

    while ! cat /tmp/clusters | sort | uniq | wc -l | awk '{print $1}' | grep -q "^${clusters}$"
    do
      curl http://$svc_name:8080 2> /dev/null >> /tmp/clusters
      sleep 1
    done

    cat /tmp/clusters | sort | uniq -c
    sleep 1000000
