apiVersion: v1
kind: Pod
metadata:
  name: go-web-server-pod
  labels:
    app: go-web-server-pod
spec:
  containers:
    - name: go-web-server
      image: ttl.sh/littlejo-webapp:2h
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: cluster

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/global: "true"
  labels:
    app: go-web-server-pod
  name: go-web-server-pod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-web-server-pod
  type: ClusterIP
