apiVersion: v1
kind: Pod
metadata:
  name: go-web-server-pod
  namespace: default
  labels:
    app: go-web-server-pod
spec:
  containers:
    - name: go-web-server
      image: ttl.sh/littlejo-webapp:3h
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: cluster
