name: Dockerbuild
env:
  WEBAPP_IMAGE: "quay.io/littlejo83/webapp:0.1"
on:
  push:
    branches:
      - main
    paths:
    - 'web-server/docker/*'
  pull_request:
    paths:
    - 'web-server/docker/*'
    paths-ignore:
      - '*/README.md'
jobs:
  build-test:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_PW }}

    - name: Docker build
      run: |
        cd web-server/docker/
        docker buildx build --platform linux/arm64,linux/amd64 -t $WEBAPP_IMAGE --push .
